:- module(content, [author/2, post/7]).

% Authors
% author ID, display name
author(aarroyoc, "Adrián Arroyo Calle").

% Post
% Slug (ID), title, author, date, content, status, tags

post("bosque-lenguaje-programacion-microsoft", "Bosque, el nuevo lenguaje de programación de Microsoft", aarroyoc, "2019-04-24 16:12:49.419479", html("bosque-lenguaje-programacion-microsoft.html"), public, ["lenguaje","bosque","programacion","microsoft"]).
post("introduccion-a-la-orientacion", "Introducción a la orientación", aarroyoc, "2013-12-15 00:00:00", html("introduccion-a-la-orientacion.html"), public, ["republica"]).
post("faqs", "FAQs", aarroyoc, "2000-01-01 00:00:00", html("faqs.html"), public, ["faqs"]).
post("cosas-no-sabias-python", "Cosas que (probablemente) no sabías de Python", aarroyoc, "2019-06-09 15:13:38.339585", html("cosas-no-sabias-python.html"), public, ["programacion","tutorial","python"]).
post("web-semantica-rdf", "Web Semántica desde cero: RDF", aarroyoc, "2019-07-16 20:11:15.981079", html("web-semantica-rdf.html"), public, ["xml","programacion","linked data","semantica","rdf","json-ld","web"]).
post("web-semantica-rdf-schema", "Web Semántica desde cero: RDF Schema", aarroyoc, "2019-07-18 12:43:45.857618", html("web-semantica-rdf-schema.html"), public, ["programacion","schema","semantica","ontologia","rdf","web"]).
post("programacion-web-prolog", "Programación web en Prolog", aarroyoc, "2019-04-25 17:22:18.557386", html("programacion-web-prolog.html"), public, ["swi","programacion","prolog","web"]).
post("minikanren-programacion-logica", "miniKanren, programación lógica diminuta", aarroyoc, "2019-06-14 16:58:44.104901", html("minikanren-programacion-logica.html"), public, ["prolog","programacion","tutorial","minikanren","python"]).
post("web-semantica-sparql", "Web Semántica desde cero: SPARQL", aarroyoc, "2019-07-19 21:06:08.241138", html("web-semantica-sparql.html"), public, ["programacion","web semantica","tutorial","sparql","rdf","web"]).
post("portaudio-libsndfile-reproducir-ogg-vorbis-flac-y-wav-en-c", "PortAudio + libsndfile. Reproducir Ogg Vorbis, FLAC y WAV en C++", aarroyoc, "2013-09-04 00:00:00", html("portaudio-libsndfile-reproducir-ogg-vorbis-flac-y-wav-en-c.html"), public, ["vorbis","programacion","audio","portaudio","linux","tutorial","cpp","flac"]).
post("azpazeta-2-0-juno-disponible-a-partir-de-hoy", "Azpazeta 2.0 Juno. Disponible a partir de hoy.", aarroyoc, "2013-09-25 00:00:00", html("azpazeta-2-0-juno-disponible-a-partir-de-hoy.html"), public, ["republica"]).
post("la-mistica-relacion-entre-el-9n-y-firefox", "La mística relación entre el 9N y Firefox", aarroyoc, "2014-10-08 00:00:00", html("la-mistica-relacion-entre-el-9n-y-firefox.html"), public, ["cataluna","firefox","complot","politica","republica","bug","mozilla","extensiones"]).
post("web-semantica-linked-data-solid", "Web Semántica desde cero: Linked Data y SOLID", aarroyoc, "2019-07-22 16:24:47.604735", html("web-semantica-linked-data-solid.html"), public, ["programacion","web semantica","tutorial","solid","sparql","rdf","web"]).
post("crea-tu-primer-paquete-para-haiku", "Crea tu primer paquete para Haiku", aarroyoc, "2015-04-03 00:00:00", html("crea-tu-primer-paquete-para-haiku.html"), public, ["haikuports","programacion","paqueteria","haikudepot","haikuporter","gcc","haiku"]).
post("advent-of-code-2018-segunda-semana", "Advent of Code 2018: segunda semana", aarroyoc, "2018-12-16 00:00:00", html("advent-of-code-2018-segunda-semana.html"), public, ["programacion","advent-of-code","algoritmia","algoritmos","python"]).
post("la-gestion-de-la-memoria-en-rust", "La gestión de la memoria en Rust", aarroyoc, "2015-05-22 00:00:00", html("la-gestion-de-la-memoria-en-rust.html"), public, ["programacion","linux","rust","memoria","cplusplus"]).
post("tutorial-de-cmake", "Tutorial de CMake", aarroyoc, "2015-06-22 00:00:00", html("tutorial-de-cmake.html"), public, ["programacion","linux","cmake","tutorial","cpp"]).
post("tutorial-wix-windows-installer-msi", "Tutorial de WiX (Windows Installer MSI)", aarroyoc, "2015-09-03 00:00:00", html("tutorial-wix-windows-installer-msi.html"), public, ["xml","programacion","tutorial","cpp","windows","microsoft","wix","instalador"]).
post("eurocookie-js", "eurocookie-js", aarroyoc, "2015-09-16 00:00:00", html("eurocookie-js.html"), public, ["programacion","europa","bower","javascript","npm","cookies"]).
post("proyecto-ceres", "Proyecto Ceres", aarroyoc, "2015-06-04 00:00:00", html("proyecto-ceres.html"), public, ["dmaic","programacion","addon-sdk","deming","javascript","firefox","calidad","webextensions","extensiones"]).
post("subir-apk-google-play-automaticamente", "Subir APK a Google Play automáticamente", aarroyoc, "2016-07-26 00:00:00", html("subir-apk-google-play-automaticamente.html"), public, ["programacion","google","google-play","javascript","oauth2","apk","android","nodejs","script"]).
post("api-adrianistan", "API de Adrianistán", aarroyoc, "2019-02-13 19:06:42.648347", html("api-adrianistan.html"), public, ["sparql","api","programacion","blog"]).
post("que-paso-con-web-semantica", "¿Qué pasó con la Web Semántica?", aarroyoc, "2019-03-10 10:56:10.917942", html("que-paso-con-web-semantica.html"), public, ["programacion","web semantica","sparql","rdf","web"]).
post("ya-he-logrado-dominar-mundo", "Ya he logrado dominar el mundo", aarroyoc, "2015-12-28 00:00:00", html("ya-he-logrado-dominar-mundo.html"), public, ["humor","nwo","risa","republica","mundial","dominacion","santos-inocentes"]).
post("usar-ava-para-tests-en-una-api-hecha-en-node-js-y-express", "Usar AVA para tests en una API hecha en Node.js y Express", aarroyoc, "2018-07-15 00:00:00", html("usar-ava-para-tests-en-una-api-hecha-en-node-js-y-express.html"), public, ["api","programacion","javascript","tutorial","ava","supertest","nodejs","test","node-js"]).
post("conclusiones-de-la-visita-de-richard-stallman-a-valladolid", "Conclusiones de la visita de Richard Stallman a Valladolid", aarroyoc, "2018-12-04 00:00:00", html("conclusiones-de-la-visita-de-richard-stallman-a-valladolid.html"), public, ["programacion","linux","stallman","conferencia","fsf","gpl"]).
post("beta-privada-tuctum-ga-la-red-social-te-paga", "Beta privada de TucTum, la red social que te paga", aarroyoc, "2016-08-15 00:00:00", html("beta-privada-tuctum-ga-la-red-social-te-paga.html"), public, ["programacion","satoshi","bitcoin","javascript","beta","invitaciones","gnu-social","tuctum","anuncios","tsu","red-social"]).
post("mozilla-desiste-rust-sera-sustituido-jai", "Mozilla desiste, Rust será sustituido por Jai", aarroyoc, "2016-12-28 00:00:00", html("mozilla-desiste-rust-sera-sustituido-jai.html"), public, ["lenguaje","programacion","rust","jai","mozilla"]).
post("emulando-linus-torvalds-crea-propio-sistema-operativo-desde-0-ii", "Emulando a Linus Torvalds: Crea tu propio sistema operativo desde 0 (II)", aarroyoc, "2015-11-27 00:00:00", html("emulando-linus-torvalds-crea-propio-sistema-operativo-desde-0-ii.html"), public, ["programacion","sistemas-operativos","kernel","colores","linux","panic","desdelinux","next-divel","vga"]).
post("9front-fork-plan9-desarrollado-dementes", "9front, un fork de Plan9 desarrollado por dementes", aarroyoc, "2017-01-16 00:00:00", html("9front-fork-plan9-desarrollado-dementes.html"), public, ["plan9","clinton","orwell","programacion","sistemas-operativos","unix","humor","guerra-fria","linux","kissinger","codigo-de-conducta","9front"]).
post("funciones-closures-rust", "Funciones y closures en Rust", aarroyoc, "2017-07-03 00:00:00", html("funciones-closures-rust.html"), public, ["programacion","genericidad","rust","tutorial","closures","lambda"]).
post("concurrencia-en-rust", "Concurrencia en Rust", aarroyoc, "2017-07-03 00:00:00", html("concurrencia-en-rust.html"), public, ["thread","hilo","programacion","rust","tutorial","parallel","mutex"]).
post("mapas-interactivos-html5-snapsvg", "Mapas interactivos en HTML5 con SnapSVG", aarroyoc, "2016-03-06 00:00:00", html("mapas-interactivos-html5-snapsvg.html"), public, ["programacion","gamedev","juegos","javascript","mapas","svg","programacion-de-videojuegos","html5"]).
post("lo-debes-las-tarjetas-credito-debito-prepago", "Todo lo que debes sobre las tarjetas de crédito, débito y prepago", aarroyoc, "2017-07-27 00:00:00", html("lo-debes-las-tarjetas-credito-debito-prepago.html"), public, ["prepago","programacion","monedero","visa","debito","unionpay","maestro","mastercard","rfid","cirrus","emv","tarjetas","nfc","3dsecure","credito"]).
post("presentacion", "Presentación", aarroyoc, "2012-10-25 00:00:00", html("presentacion.html"), public, ["republica"]).
post("cronica-la-62-seminci", "Crónica de la 62 SEMINCI", aarroyoc, "2017-11-12 00:00:00", html("cronica-la-62-seminci.html"), public, ["valladolid","republica","cine","jurado","seminci"]).
post("enebro-robot-automatico-forex-javascript", "Enebro, un robot automático para FOREX en JavaScript", aarroyoc, "2016-03-12 00:00:00", html("enebro-robot-automatico-forex-javascript.html"), public, ["enebro","programacion","bolsa","uphold","javascript","forex","nodejs"]).
post("cronica-video-citas-celebres", "Crónica de un vídeo de citas célebres", aarroyoc, "2016-12-18 00:00:00", html("cronica-video-citas-celebres.html"), public, ["subtitulos","srt","programacion","aforismos","javascript","regex","ffmpeg","videojuegos","video","mp4","node-js","the-witness"]).
post("estadistica-python-ajustar-datos-una-distribucion-parte-vii", "Estadística en Python: ajustar datos a una distribución (parte VII)", aarroyoc, "2018-01-17 00:00:00", html("estadistica-python-ajustar-datos-una-distribucion-parte-vii.html"), public, ["big-data","kolmogorov","programacion","scipy","estadistica","data-science","tutorial","chi-cuadrado","python"]).
post("hablando-sobre-google-code-in-2012-y-proyectos", "Hablando sobre Google Code-in 2012 y proyectos", aarroyoc, "2013-02-06 00:00:00", html("hablando-sobre-google-code-in-2012-y-proyectos.html"), public, ["republica"]).
post("territorios-espanoles-olvidados", "Territorios españoles olvidados", aarroyoc, "2013-10-10 00:00:00", html("territorios-espanoles-olvidados.html"), public, ["republica"]).
post("fliuva-o-como-crear-un-servicio-de-analiticas", "Fliuva, o como crear un servicio de analíticas", aarroyoc, "2015-04-06 00:00:00", html("fliuva-o-como-crear-un-servicio-de-analiticas.html"), public, ["programacion","estadistica","analiticas","express","javascript","nodejs"]).
post("alojando-una-web-en-ipfs", "Alojando una web en IPFS", aarroyoc, "2018-09-24 00:00:00", html("alojando-una-web-en-ipfs.html"), public, ["dns","programacion","ipfs","javascript","linux","tutorial","systemd","jekyll","hugo","web"]).
post("la-semana-en-adrianistan-ii", "La semana en Adrianistán II", aarroyoc, "2014-06-02 00:00:00", html("la-semana-en-adrianistan-ii.html"), public, ["republica"]).
post("opengl-y-su-gran-futuro", "OpenGL y su gran futuro", aarroyoc, "2013-03-14 00:00:00", html("opengl-y-su-gran-futuro.html"), public, ["republica"]).
post("intercambio-con-francia", "Intercambio con Francia", aarroyoc, "2013-04-19 00:00:00", html("intercambio-con-francia.html"), public, ["republica"]).
post("la-fuente-q-y-el-problema-sinoptico", "La Fuente Q y el problema sinóptico", aarroyoc, "2013-05-16 00:00:00", html("la-fuente-q-y-el-problema-sinoptico.html"), public, ["religion-y-filosofia"]).
post("natural-language-understanding-con-snips-nlu-en-python", "Natural Language Understanding con Snips NLU en Python", aarroyoc, "2018-04-17 00:00:00", html("natural-language-understanding-con-snips-nlu-en-python.html"), public, ["inteligencia-artificial","programacion","snips","nlu","tutorial","machine-learning","python"]).
post("rust-101-tutorial-rust-espanol", "Rust 101, tutorial de Rust en español", aarroyoc, "2017-07-03 00:00:00", html("rust-101-tutorial-rust-espanol.html"), public, ["rust"]).
post("calculadora-de-4-bits", "Calculadora de 4 Bits", aarroyoc, "2013-05-28 00:00:00", html("calculadora-de-4-bits.html"), public, ["republica"]).
post("la-semana-en-adrianistan-i", "La semana en Adrianistán I", aarroyoc, "2014-05-26 00:00:00", html("la-semana-en-adrianistan-i.html"), public, ["republica"]).
post("smartos-una-introduccion", "SmartOS, una introducción", aarroyoc, "2014-10-13 00:00:00", html("smartos-una-introduccion.html"), public, ["programacion","solaris","kvm","illumos","smartos"]).
post("post-mortem-de-torre-utopia", "Post Mortem de Torre Utopía", aarroyoc, "2015-01-22 00:00:00", html("post-mortem-de-torre-utopia.html"), public, ["programacion","typescript","gamedev","clay-io","fgl","programacion-de-videojuegos","npm","marketplace","kongregate","postmortem","html5","gamejs"]).
post("la-experiencia-gci-2014-con-haiku", "La experiencia GCI 2014 con Haiku", aarroyoc, "2015-01-23 00:00:00", html("la-experiencia-gci-2014-con-haiku.html"), public, ["haikuports","programacion","2015","gci","haikutodo","freecell","libuv","todo","beapi","openscenegraph","superfreecell","opensource","haiku"]).
post("preparando-el-nuevo-curso", "Preparando el nuevo curso", aarroyoc, "2013-08-26 00:00:00", html("preparando-el-nuevo-curso.html"), public, ["republica"]).
post("inicio-del-nuevo-curso-novedades-interesantes", "Inicio del nuevo curso. Novedades interesantes", aarroyoc, "2013-10-03 00:00:00", html("inicio-del-nuevo-curso-novedades-interesantes.html"), public, ["republica"]).
post("secta-sectarium-javascript-vs-rust", "Secta Sectarium, JavaScript vs Rust", aarroyoc, "2015-03-06 00:00:00", html("secta-sectarium-javascript-vs-rust.html"), public, ["tycoon","programacion","gamedev","gulp","javascript","secta-sectarium","programacion-de-videojuegos","nodejs","typescript"]).
post("algunos-proyectos-open-source-con-los-que-colaboro", "Algunos proyectos open-source con los que colaboro", aarroyoc, "2013-10-07 00:00:00", html("algunos-proyectos-open-source-con-los-que-colaboro.html"), public, ["republica"]).
post("js13k-miss-city-postmortem", "js13k y Miss City (postmortem)", aarroyoc, "2015-09-20 00:00:00", html("js13k-miss-city-postmortem.html"), public, ["programacion","gamedev","gulp","javascript","js13k","competicion","programacion-de-videojuegos","concurso","postmortem","html5"]).
post("esperanto-interlengua-y-cia", "Esperanto, Interlengua y cía.", aarroyoc, "2013-10-07 00:00:00", html("esperanto-interlengua-y-cia.html"), public, ["republica"]).
post("la-semana-en-adrianistan-iii", "La Semana en Adrianistán III", aarroyoc, "2014-06-09 00:00:00", html("la-semana-en-adrianistan-iii.html"), public, ["republica"]).
post("la-semana-en-adrianistan-iv", "La Semana en Adrianistán (IV)", aarroyoc, "2014-06-17 00:00:00", html("la-semana-en-adrianistan-iv.html"), public, ["republica"]).
post("mis-predicciones-para-el-futuro-en-lenguajes-de-programacion-i", "Mis predicciones para el futuro (en lenguajes de programación) I", aarroyoc, "2014-07-02 00:00:00", html("mis-predicciones-para-el-futuro-en-lenguajes-de-programacion-i.html"), public, ["programacion","javascript","rust","cpp","perl","php","python"]).
post("pajaro-bebedor", "El pájaro que nunca deja de beber", aarroyoc, "2015-12-23 00:00:00", html("pajaro-bebedor.html"), public, ["fisica","simpsons","video"]).
post("gajse-una-carta-de-presentacion", "GAJSE, una carta de presentación", aarroyoc, "2014-07-28 00:00:00", html("gajse-una-carta-de-presentacion.html"), public, ["republica"]).
post("probando-jekyll", "Probando Jekyll", aarroyoc, "2014-08-05 00:00:00", html("probando-jekyll.html"), public, ["republica"]).
post("la-odisea-de-una-aplicacion-comercial-hecha-en-ogre-y-cegui", "La Odisea de una aplicación comercial hecha en Ogre y CEGUI", aarroyoc, "2014-08-30 00:00:00", html("la-odisea-de-una-aplicacion-comercial-hecha-en-ogre-y-cegui.html"), public, ["ogre","programacion","paqueteria","cegui","linux","programacion-de-videojuegos","ubuntu"]).
post("lumtumo-ya-es-open-source", "Lumtumo ya es open source", aarroyoc, "2014-09-25 00:00:00", html("lumtumo-ya-es-open-source.html"), public, ["ogre","programacion","mit","videojuego","bitbucket","cpp","programacion-de-videojuegos","lumtumo","opensource"]).
post("esqueleto-de-juegos-npm", "Esqueleto de juegos NPM", aarroyoc, "2014-10-26 00:00:00", html("esqueleto-de-juegos-npm.html"), public, ["programacion","gamedev","javascript","grunt","programacion-de-videojuegos","npm","nodejs"]).
post("prosperidad", "Prosperidad", aarroyoc, "2014-12-26 00:00:00", html("prosperidad.html"), public, ["2015","2014","valores","objetivos","republica","recapitulacion","postmortem","futuro"]).
post("usando-node-con-xulrunner-y-gecko", "Usando Node con XULRunner y Gecko", aarroyoc, "2015-02-24 00:00:00", html("usando-node-con-xulrunner-y-gecko.html"), public, ["gecko","programacion","javascript","firefox","nodejs","html5"]).
post("introduccion-a-d-bus", "Introducción a D-Bus", aarroyoc, "2015-02-28 00:00:00", html("introduccion-a-d-bus.html"), public, ["programacion","javascript","linux","dbus","ubuntu"]).
post("la-gran-lista-bitcoins-gratis", "La gran lista de BitCoins gratis", aarroyoc, "2015-10-04 00:00:00", html("la-gran-lista-bitcoins-gratis.html"), public, ["bitcoin","gratis","lista","fauce","republica"]).
post("instala-programas-en-haiku-con-haikuports-y-haikuporter", "Instala programas en Haiku con HaikuPorts y HaikuPorter", aarroyoc, "2015-04-02 00:00:00", html("instala-programas-en-haiku-con-haikuports-y-haikuporter.html"), public, ["programacion","paqueteria","haikudepot","tutorial","pkgman","paquete","haiku"]).
post("nexcono-sitio-viral-preferido", "NexCono, tu sitio viral preferido", aarroyoc, "2015-07-13 00:00:00", html("nexcono-sitio-viral-preferido.html"), public, ["nexcono","republica","webs-viral"]).
post("la-informacion-es-poder", "La información es poder", aarroyoc, "2015-04-05 00:00:00", html("la-informacion-es-poder.html"), public, ["programacion","estadistica","analiticas","javascript","nodejs","openshift"]).
post("aprobar-consiste-en-entrar-en-el-juego", "Aprobar consiste en entrar en el juego", aarroyoc, "2015-04-08 00:00:00", html("aprobar-consiste-en-entrar-en-el-juego.html"), public, ["juego","complot","aprobar","imagen","republica","meme"]).
post("crea-tu-propio-lenguaje-de-programacion", "Crea tu propio lenguaje de programación", aarroyoc, "2015-05-13 00:00:00", html("crea-tu-propio-lenguaje-de-programacion.html"), public, ["maquinavirtual","programacion","perin","rust"]).
post("literatura-adrianistani-libro-ligero-relatos-cortos", "Literatura Adrianistaní, un libro ligero de relatos cortos", aarroyoc, "2015-06-14 00:00:00", html("literatura-adrianistani-libro-ligero-relatos-cortos.html"), public, ["novela","relato-corto","escribir","libro","literatura","libros"]).
post("easter-egg-linux-la-syscall-reboot", "Easter egg en Linux: la syscall reboot", aarroyoc, "2015-07-11 00:00:00", html("easter-egg-linux-la-syscall-reboot.html"), public, ["linux","programacion","easter-egg","curiosidades"]).
post("secta-sectarium-documentacion-e-investigacion", "Secta Sectarium, documentación e investigación", aarroyoc, "2015-03-08 00:00:00", html("secta-sectarium-documentacion-e-investigacion.html"), public, ["secta","teologia","documentacion","investigacion","videojuegos","religion","religion-y-filosofia"]).
post("rust-essentials", "Rust Essentials, reseña del libro", aarroyoc, "2015-07-17 00:00:00", html("rust-essentials.html"), public, ["programacion","resena","review","linux","rust","libro","libros"]).
post("haz-scripts", "¡Haz scripts!", aarroyoc, "2015-08-04 00:00:00", html("haz-scripts.html"), public, ["bash","programacion","scripts","javascript","linux","perl","nodejs","python"]).
post("la-criptonovela-del-verano-una-historia-tres-capitulos-capitulo-2", "La Criptonovela del verano: una historia en tres capítulos (Capítulo 2)", aarroyoc, "2016-08-28 00:00:00", html("la-criptonovela-del-verano-una-historia-tres-capitulos-capitulo-2.html"), public, ["programacion","bolsa","hard-fork","bitcoin","ethereum","smartcontracts","criptodivisa"]).
post("hercolubus-planeta-rojo", "Hercólubus o planeta rojo", aarroyoc, "2015-11-21 00:00:00", html("hercolubus-planeta-rojo.html"), public, ["secta","libro","religion","literatura","libros","religion-y-filosofia"]).
post("probando-openindiana", "Probando OpenIndiana", aarroyoc, "2015-08-14 00:00:00", html("probando-openindiana.html"), public, ["openindiana","programacion","sistemas-operativos","solaris","linux","illumos"]).
post("usar-gnu-parallel-aumentar-rendimiento-tus-scripts", "Usar GNU Parallel para aumentar el rendimiento de tus scripts", aarroyoc, "2015-10-20 00:00:00", html("usar-gnu-parallel-aumentar-rendimiento-tus-scripts.html"), public, ["bash","programacion","optipng","linux","parallel","ffmpeg","gnu","script"]).
post("emulando-linus-torvalds-crea-propio-sistema-operativo-desde-0-i", "Emulando a Linus Torvalds: Crea tu propio sistema operativo desde 0 (I)", aarroyoc, "2015-11-26 00:00:00", html("emulando-linus-torvalds-crea-propio-sistema-operativo-desde-0-i.html"), public, ["programacion","sistemas-operativos","kernel","grub","linux","retro","desdelinux","cpp","qemu"]).
post("analisis-the-witness", "Análisis de The Witness", aarroyoc, "2016-03-25 00:00:00", html("analisis-the-witness.html"), public, ["resena","review","puzzle","analisis","isla","witness","videojuegos","rompecabezas"]).
post("ano-nuevo-blog-nuevo", "Año nuevo, blog nuevo", aarroyoc, "2019-02-11 21:44:53.574008", html("ano-nuevo-blog-nuevo.html"), public, ["programacion"]).
post("ante-la-falta-espacio-android", "¿Qué hacer ante la falta de espacio en Android?", aarroyoc, "2015-08-02 00:00:00", html("ante-la-falta-espacio-android.html"), public, ["programacion","espacio","root","tips","android","moviles"]).
post("emulando-linus-torvalds-crea-propio-sistema-operativo-desde-0-iii", "Emulando a Linus Torvalds: Crea tu propio sistema operativo desde 0 (III)", aarroyoc, "2015-11-28 00:00:00", html("emulando-linus-torvalds-crea-propio-sistema-operativo-desde-0-iii.html"), public, ["programacion","kernel","linux","desdelinux","next-divel"]).
post("emulando-linus-torvalds-crea-propio-sistema-operativo-desde-0-iv", "Emulando a Linus Torvalds: Crea tu propio sistema operativo desde 0 (IV)", aarroyoc, "2015-11-29 00:00:00", html("emulando-linus-torvalds-crea-propio-sistema-operativo-desde-0-iv.html"), public, ["programacion","sistemas-operativos","x86","kernel","linux","gdt","next-divel"]).
post("primer-debug-primeros-pasos-gdb-valgrind-strace", "Mi primer debug. Primeros pasos con gdb, Valgrind y strace.", aarroyoc, "2015-12-04 00:00:00", html("primer-debug-primeros-pasos-gdb-valgrind-strace.html"), public, ["programacion","linux","c","cpp","valgrind","depurar","debug","gdb","strace"]).
post("emulando-linus-torvalds-crea-propio-sistema-operativo-desde-0-vii", "Emulando a Linus Torvalds: Crea tu propio sistema operativo desde 0 (VII)", aarroyoc, "2015-12-02 00:00:00", html("emulando-linus-torvalds-crea-propio-sistema-operativo-desde-0-vii.html"), public, ["programacion","sistemas-operativos","x86","kernel","linux","desdelinux","next-divel","timer"]).
post("bienvenido-2016-bienvenido-kaizen", "Bienvenido 2016, bienvenido kaizen", aarroyoc, "2016-01-08 00:00:00", html("bienvenido-2016-bienvenido-kaizen.html"), public, ["kaizen","social","republica","calidad"]).
post("kovel-1-0-disena-modelos-3d-usando-voxeles", "Kovel 1.0, diseña modelos en 3D usando vóxeles", aarroyoc, "2016-01-09 00:00:00", html("kovel-1-0-disena-modelos-3d-usando-voxeles.html"), public, ["3d","opengl","programacion","lanzamiento","linux","voxel","windows","programacion-de-videojuegos","graficos","kovel","haiku"]).
post("programar-c-2016", "¿Cómo programar en C (en 2016)?", aarroyoc, "2016-01-10 00:00:00", html("programar-c-2016.html"), public, ["2016","programacion","pautas","c","cpp","buenas-practicas"]).
post("ethereum-y-smartcontracts", "Ethereum y SmartContracts", aarroyoc, "2016-03-02 00:00:00", html("ethereum-y-smartcontracts.html"), public, ["programacion","bolsa","bitcoin","ethereum","codius","smartcontracts"]).
post("convertir-a-haiku-en-rolling-release", "Convertir a Haiku en rolling release", aarroyoc, "2015-01-31 00:00:00", html("convertir-a-haiku-en-rolling-release.html"), public, ["rolling-release","pkgman","programacion","haiku"]).
post("crear-credenciales-oauth2-para-google", "Crear credenciales OAuth2 para Google", aarroyoc, "2016-07-26 00:00:00", html("crear-credenciales-oauth2-para-google.html"), public, ["api","programacion","google","http","token","javascript","oauth2","credenciales"]).
post("cuando-bad_style-se-convierte-algo-ofensivo", "Cuando 'bad_style' se convierte en algo ofensivo", aarroyoc, "2017-06-20 00:00:00", html("cuando-bad_style-se-convierte-algo-ofensivo.html"), public, ["orwell","chomsky","rust","politica","zizek","libertad","node-js","filosofia","religion-y-filosofia"]).
post("ipfs-el-futuro-de-la-web-descentralizada", "IPFS, el futuro de la web descentralizada", aarroyoc, "2018-09-19 00:00:00", html("ipfs-el-futuro-de-la-web-descentralizada.html"), public, ["torrent","programacion","ipfs","linux","tutorial","p2p","web"]).
post("tutorial-gnu-cash", "Tutorial de GnuCash en castellano", aarroyoc, "2016-07-13 00:00:00", html("tutorial-gnu-cash.html"), public, ["bolsa","tutorial","pyme","gnucash","republica","contabilidad","dinero","software"]).
post("formulario-registro-elm", "Formulario de registro en Elm", aarroyoc, "2017-07-15 00:00:00", html("formulario-registro-elm.html"), public, ["programacion","javascript","tutorial","formulario","elm"]).
post("generar-frases-cadenas-markov-machine-learning-python", "Generar frases con cadenas de Markov. Machine Learning en Python", aarroyoc, "2018-01-25 00:00:00", html("generar-frases-cadenas-markov-machine-learning-python.html"), public, ["programacion","python","tutorial","machine-learning","haiku","markov"]).
post("la-fisica-parte-1", "Sobre la Física - Parte 1", aarroyoc, "2016-03-27 00:00:00", html("la-fisica-parte-1.html"), public, ["religion-y-filosofia","ciencia","meditacion","pensamiento","fisica","filosofia","empirismo"]).
post("miri-maquina-virtual-rust", "Miri: una máquina virtual para Rust", aarroyoc, "2019-04-18 12:15:18.621082", html("miri-maquina-virtual-rust.html"), public, ["programacion","interprete","rust","miri","memoria","maquina virtual","test"]).
post("repaso-las-aplicaciones-haiku", "Un repaso por las aplicaciones de Haiku", aarroyoc, "2015-07-01 00:00:00", html("repaso-las-aplicaciones-haiku.html"), public, ["programacion","review","haiku","aplicaciones"]).
post("programando-chromecast-desde-javascript", "Programando el Chromecast desde JavaScript", aarroyoc, "2016-04-02 00:00:00", html("programando-chromecast-desde-javascript.html"), public, ["programacion","google","javascript","chromecast","nodejs","html5"]).
post("la-fisica-parte-2-la-luz", "Sobre la Física - Parte 2 - ¿Qué es la luz?", aarroyoc, "2016-04-14 00:00:00", html("la-fisica-parte-2-la-luz.html"), public, ["ciencia","fisicia","maxwell","newton","luz","naturaleza","fisica","einstein"]).
post("tutorial-webextensions-i-manifest-json-conceptos", "Tutorial de WebExtensions (I) - manifest.json y conceptos", aarroyoc, "2016-10-01 00:00:00", html("tutorial-webextensions-i-manifest-json-conceptos.html"), public, ["programacion","manifest","chrome","javascript","xul","firefox","edge","tutorial","opera","webextensions","json","xpcom"]).
post("nuevo-comienzo", "Un nuevo comienzo", aarroyoc, "2020-06-29 22:50:50.667729", html("nuevo-comienzo.html"), public, ["telefonica","personal","trabajo"]).
post("ocurrira-bitcoin-los-ordenadores-cuanticos", "¿Qué ocurrirá con Bitcoin y los ordenadores cuánticos?", aarroyoc, "2016-05-07 00:00:00", html("ocurrira-bitcoin-los-ordenadores-cuanticos.html"), public, ["pregunta","bolsa","dwave","bitcoin","cuantico"]).
post("the-everything-building", "The Everything Building", aarroyoc, "2016-05-09 00:00:00", html("the-everything-building.html"), public, ["gamedev","ascensor","html5","videojuegos","ludumdare","arcade"]).
post("fundamentalismo-ateo", "Fundamentalismo ateo", aarroyoc, "2016-12-21 00:00:00", html("fundamentalismo-ateo.html"), public, ["ateo","fundamentalismo","richard-dawkins","religion","agnostico","religion-y-filosofia"]).
post("valladolid-hyperlapse", "Valladolid Hyperlapse", aarroyoc, "2016-05-11 00:00:00", html("valladolid-hyperlapse.html"), public, ["timelapse","valladolid","cultura","republica","turismo","hyperlapse"]).
post("programando-haiku-bapplication-bwindow-bbutton-parte-i", "Programando para Haiku - BApplication, BWindow y BButton - Parte I", aarroyoc, "2016-05-18 00:00:00", html("programando-haiku-bapplication-bwindow-bbutton-parte-i.html"), public, ["programacion","beos","ventana","cpp","aplicacion","haiku"]).
post("tutorial-hugo-espanol-generador-sitios-estaticos", "Tutorial de Hugo en español, generador de sitios estáticos", aarroyoc, "2016-05-26 00:00:00", html("tutorial-hugo-espanol-generador-sitios-estaticos.html"), public, ["cms","programacion","html","jekyll","hugo","blog","go","web"]).
post("programando-haiku-file-panel-parte-ii", "Programando para Haiku - File panel - Parte II", aarroyoc, "2016-06-04 00:00:00", html("programando-haiku-file-panel-parte-ii.html"), public, ["bmessage","programacion","beos","filepanel","cpp","bmessenger","haiku"]).
post("shortkin-gq", "ShortKin.gq, un acortador de enlaces anónimo", aarroyoc, "2016-08-04 00:00:00", html("shortkin-gq.html"), public, ["acortar","api","programacion","javascript","acortador","heroku","enlaces","shortkingq","shortener"]).
post("programando-haiku-barras-menus-parte-iii", "Programando para Haiku - Barras de menús - Parte III", aarroyoc, "2016-08-17 00:00:00", html("programando-haiku-barras-menus-parte-iii.html"), public, ["api","programacion","beos","menu","gui","tutorial","menubar","cpp","haiku"]).
post("la-criptonovela-del-verano-una-historia-tres-capitulos-capitulo-1", "La Criptonovela del verano: una historia en tres capítulos (Capítulo 1)", aarroyoc, "2016-08-27 00:00:00", html("la-criptonovela-del-verano-una-historia-tres-capitulos-capitulo-1.html"), public, ["programacion","bolsa","novela","bitcoin","satoshi","fork","linux","core","historia","unlimited","classic"]).
post("la-criptonovela-del-verano-una-historia-tres-capitulos-capitulo-3", "La Criptonovela del verano: una historia en tres capítulos (Capítulo 3)", aarroyoc, "2016-08-30 00:00:00", html("la-criptonovela-del-verano-una-historia-tres-capitulos-capitulo-3.html"), public, ["programacion","bolsa","bitcoin","exchange","mtgox","juicio","robo","bitfinex","bfx","criptodivisa"]).
post("el-universo-mecanico", "El Universo Mecánico", aarroyoc, "2016-05-10 00:00:00", html("el-universo-mecanico.html"), public, ["universo","ciencia","aprender","documental","fisica"]).
post("camino-a-prolog-backtracking", "El camino a Prolog: obtener soluciones y no determinismo (parte II)", aarroyoc, "2023-01-02 13:36:13.201548", html("camino-a-prolog-backtracking.html"), public, ["prolog","programacion","backtracking","tutorial"]).
post("usando-iron-web-framework-rust", "Usando Iron, un web framework para Rust", aarroyoc, "2016-11-20 00:00:00", html("usando-iron-web-framework-rust.html"), public, ["programacion","server","http","express","rust","crate","web-framework","web"]).
post("viernes-complot-adrianistan", "Viernes de Complot en Adrianistán", aarroyoc, "2016-11-24 00:00:00", html("viernes-complot-adrianistan.html"), public, ["arduino","afiliados","comprar","viernes-de-complot","electronica","black-friday","raspberry-pi","republica","tiendas","libros","ofertas"]).
post("tutorial-neon-combina-node-js-rust", "Tutorial de Neon - Combina Node.js con Rust", aarroyoc, "2017-01-27 00:00:00", html("tutorial-neon-combina-node-js-rust.html"), public, ["npm","programacion","javascript","linux","rust","markdown","neon","nodejs","node-js"]).
post("esta-usted-broma-sr-feynman", "¿Está usted de broma Sr. Feynman?", aarroyoc, "2017-02-16 00:00:00", html("esta-usted-broma-sr-feynman.html"), public, ["feynman","anecdota","richard","libro","fisica","biografia","libros"]).
post("nace-foro-gamedev-hispano", "Nace el foro Gamedev Hispano", aarroyoc, "2016-12-05 00:00:00", html("nace-foro-gamedev-hispano.html"), public, ["programacion","gamedev","hispano","babylon","programacion-de-videojuegos","phaser","foro"]).
post("emulando-linus-torvalds-crea-propio-sistema-operativo-desde-0-v", "Emulando a Linus Torvalds: Crea tu propio sistema operativo desde 0 (V)", aarroyoc, "2015-11-30 00:00:00", html("emulando-linus-torvalds-crea-propio-sistema-operativo-desde-0-v.html"), public, ["programacion","sistemas-operativos","kernel","exception","linux","next-divel"]).
post("estadistica-python-pandas-numpy-scipy-parte-i", "Estadística en Python: Pandas, NumPy, SciPy (Parte I)", aarroyoc, "2017-10-31 00:00:00", html("estadistica-python-pandas-numpy-scipy-parte-i.html"), public, ["big-data","programacion","scipy","estadistica","data-science","matplotlib","tutorial","pandas","numpy","python"]).
post("tutorial-webextensions-ii-popup-tabs", "Tutorial de WebExtensions (II) - Popup y Tabs", aarroyoc, "2016-11-03 00:00:00", html("tutorial-webextensions-ii-popup-tabs.html"), public, ["programacion","tabs","chrome","javascript","firefox","tutorial","opera","popup","webextensions","pestanas"]).
post("cheatsheet-contenedores-rust", "Cheatsheet de contenedores de Rust", aarroyoc, "2017-10-10 00:00:00", html("cheatsheet-contenedores-rust.html"), public, ["programacion","rust","estructuras-de-datos","cheatsheet","infografia"]).
post("las-12-uvas-game-jam", "Las 12 Uvas Game Jam", aarroyoc, "2016-12-13 00:00:00", html("las-12-uvas-game-jam.html"), public, ["game-jam","programacion","gamedevhispano","gamedev","uvas","programacion-de-videojuegos","videojuegos","foro"]).
post("nuevo-lenguaje-programacion-juegos", "Un nuevo lenguaje de programación para juegos", aarroyoc, "2017-01-08 00:00:00", html("nuevo-lenguaje-programacion-juegos.html"), public, ["c17","programacion","c11","c","rust","cpp","jai","programacion-de-videojuegos","videojuegos","raii","c14","blow","excepciones","go"]).
post("tutorial-piston-programa-juegos-rust", "Tutorial de Piston, programa juegos en Rust", aarroyoc, "2017-01-17 00:00:00", html("tutorial-piston-programa-juegos-rust.html"), public, ["gfx","opengl","programacion","gamedev","glutin","libreria","linux","rust","tutorial","sdl","windows","glfw","programacion-de-videojuegos","videojuegos","piston","2d","cargo"]).
post("como-funcionan-los-sistemas-basados-en-inodos", "¿Cómo funcionan los sistemas basados en inodos?", aarroyoc, "2018-06-14 00:00:00", html("como-funcionan-los-sistemas-basados-en-inodos.html"), public, ["programacion","sistemas-operativos","sistemas-de-archivos","inodo","ext4","linux","ufs"]).
post("tutorial-maud-motor-plantillas-html-rust", "Tutorial de Maud, motor de plantillas HTML para Rust", aarroyoc, "2017-01-31 00:00:00", html("tutorial-maud-motor-plantillas-html-rust.html"), public, ["programacion","rust","template","html","crate","razor","web","plantilla","web-framework","maud"]).
post("the-pitts-circus-la-primera-pelicula-financiada-ethereum", "The Pitts Circus, la primera película financiada con Ethereum", aarroyoc, "2017-02-17 00:00:00", html("the-pitts-circus-la-primera-pelicula-financiada-ethereum.html"), public, ["entrevista","bitcoin","pelicula","crowdfunding","ethereum","inversion","circo","republica","criptodivisa"]).
post("estructuras-control-rust", "Estructuras de control en Rust", aarroyoc, "2017-07-03 00:00:00", html("estructuras-control-rust.html"), public, ["option","programacion","pattern-matching","rust","tutorial","match","result"]).
post("structs-traits-poo-rust", "Structs, traits y POO en Rust", aarroyoc, "2017-07-03 00:00:00", html("structs-traits-poo-rust.html"), public, ["programacion","struct","rust","tutorial","programacion-orientada-a-objetos","trait"]).
post("feliz-an-dame-los-datos", "Feliz añ... ¡Dame los datos!", aarroyoc, "2016-12-31 00:00:00", html("feliz-an-dame-los-datos.html"), public, ["webs","2016","2017","trafico-web","analytics","analisis","republica"]).
post("diversion-punteros-rust-bloques-unsafe", "Diversión con punteros en Rust: bloques unsafe", aarroyoc, "2017-10-12 00:00:00", html("diversion-punteros-rust-bloques-unsafe.html"), public, ["programacion","rust","c","tutorial","malloc","punteros"]).
post("rust-5-minutos-picniccode2017", "Rust en 5 minutos - #PicnicCode2017", aarroyoc, "2017-03-28 00:00:00", html("rust-5-minutos-picniccode2017.html"), public, ["programacion","valladolid","rust","post-format-video","charla","picnic-code","conferencia","uva","video"]).
post("novedades-de-c17", "Novedades de C++17", aarroyoc, "2017-04-19 00:00:00", html("novedades-de-c17.html"), public, ["c17","programacion","tuplas","novedades","estandar","linux","c","tutorial","cpp","std"]).
post("polvo", "Polvo", aarroyoc, "2017-04-26 00:00:00", html("polvo.html"), public, ["gore","polvo","relato-corto","cafe","relato","oficina","trabajo","concurso","literatura","libros"]).
post("que-pasa-con-elixir", "¿Qué pasa con Elixir?", aarroyoc, "2017-04-30 00:00:00", html("que-pasa-con-elixir.html"), public, ["lenguaje","programacion","phoenix","erlang","beam","funcional","linux","ruby","elixir","web-framework","web"]).
post("la-belleza-mips", "La belleza de MIPS", aarroyoc, "2017-05-03 00:00:00", html("la-belleza-mips.html"), public, ["programacion","cpu","hardware","linux","cpp","ensamblador","computador","mars","mips"]).
post("mandando-paquetes-icmp-echo-personalizados-python", "Mandando paquetes ICMP ECHO personalizados con Python", aarroyoc, "2017-05-10 00:00:00", html("mandando-paquetes-icmp-echo-personalizados-python.html"), public, ["programacion","redes","icmp","tutorial","wireshark","ip","python"]).
post("anrokku-videojuego-tipo-puzzle", "Anrokku, un videojuego tipo puzzle", aarroyoc, "2017-05-15 00:00:00", html("anrokku-videojuego-tipo-puzzle.html"), public, ["juego","gtk","programacion","gamedev","linux","puzzle","videojuego","cairo","descargar","programacion-de-videojuegos","python"]).
post("gestion-errores-rust-option-result", "Gestión de errores en Rust, Option y Result", aarroyoc, "2017-07-03 00:00:00", html("gestion-errores-rust-option-result.html"), public, ["option","programacion","rust","tutorial","errores","crash","result"]).
post("algoritmos-geneticos-un-caso-practico", "Algoritmos genéticos: un caso práctico", aarroyoc, "2018-12-18 00:00:00", html("algoritmos-geneticos-un-caso-practico.html"), public, ["gtk","programacion","algoritmia","linux","rust","tutorial","bezier","algoritmos-geneticos","algoritmos"]).
post("nos-vemos-la-lechazoconf", "¿Nos vemos en la LechazoConf?", aarroyoc, "2017-05-22 00:00:00", html("nos-vemos-la-lechazoconf.html"), public, ["programacion","valladolid","voy-a-estar-en","conferencia","lehazoconf"]).
post("leer-teclado-rust", "Leer de teclado en Rust", aarroyoc, "2017-09-15 00:00:00", html("leer-teclado-rust.html"), public, ["programacion","teclado","input","rust","tutorial"]).
post("feliz-navidad-prospero-2018-fractales", "¡Feliz navidad y próspero 2018! (con fractales)", aarroyoc, "2017-12-22 00:00:00", html("feliz-navidad-prospero-2018-fractales.html"), public, ["fractal","turtle","feliz-ano","programacion","koch","2018","2017","linux","rust","tutorial","navidad","python"]).
post("timers-systemd-reemplazo-cron", "Timers en systemd, reemplazo a cron", aarroyoc, "2017-07-25 00:00:00", html("timers-systemd-reemplazo-cron.html"), public, ["programacion","cron","linux","systemd","timer"]).
post("triangulo-sierpinski-javascript", "Triángulo de Sierpinski en JavaScript", aarroyoc, "2017-05-24 00:00:00", html("triangulo-sierpinski-javascript.html"), public, ["fractal","numberphile","programacion","javascript","matematicas","tutorial","sierpinski","html5","triangulo"]).
post("webassembly-tontos-usando-rust", "WebAssembly para tontos (usando Rust)", aarroyoc, "2017-06-02 00:00:00", html("webassembly-tontos-usando-rust.html"), public, ["programacion","javascript","webassembly","rust","tutorial","bytecode","emscripten"]).
post("pierdes-te-roban-movil", "¿Qué hacer si pierdes o te roban el móvil?", aarroyoc, "2017-07-07 00:00:00", html("pierdes-te-roban-movil.html"), public, ["republica"]).
post("compra-ordenadores-seminuevos-ayuda-al-medio-ambiente", "Compra ordenadores seminuevos y ayuda al medio ambiente", aarroyoc, "2017-06-28 00:00:00", html("compra-ordenadores-seminuevos-ayuda-al-medio-ambiente.html"), public, ["segunda-mano","seminuevos","republica","libreoffice","ordenadores"]).
post("referencias-prestamos-en-rust", "Referencias y préstamos en Rust", aarroyoc, "2017-07-03 00:00:00", html("referencias-prestamos-en-rust.html"), public, ["programacion","prestamo","rust","ownership","tutorial","borrow"]).
post("tests-en-rust", "Tests en Rust", aarroyoc, "2017-07-03 00:00:00", html("tests-en-rust.html"), public, ["programacion","rust","tutorial","test","cargo"]).
post("documentacion-con-rustdoc", "Documentación con rustdoc", aarroyoc, "2017-07-03 00:00:00", html("documentacion-con-rustdoc.html"), public, ["programacion","rust","documentacion","tutorial","markdown","cargo"]).
post("ha-estado-adrianistan-10-dias-offline", "¿Por qué ha estado Adrianistán 10 días offline?", aarroyoc, "2017-09-15 00:00:00", html("ha-estado-adrianistan-10-dias-offline.html"), public, ["vodafone","mastin-de-jade","peliculas","republica","raspberry-pi","cluster"]).
post("estadistica-python-media-mediana-varianza-percentiles-parte-iii", "Estadística en Python: media, mediana, varianza, percentiles (Parte III)", aarroyoc, "2017-11-04 00:00:00", html("estadistica-python-media-mediana-varianza-percentiles-parte-iii.html"), public, ["big-data","programacion","scipy","estadistica","data-science","tutorial","pandas","python"]).
post("variables-tipos-datos-rust", "Variables y tipos de datos en Rust", aarroyoc, "2017-07-03 00:00:00", html("variables-tipos-datos-rust.html"), public, ["programacion","rust","tutorial","tupla","vector"]).
post("sigo-sin-entender-nada", "Y sigo sin entender nada pero da igual", aarroyoc, "2017-09-25 00:00:00", html("sigo-sin-entender-nada.html"), public, ["cumpleanos","personal","republica","reflexion"]).
post("automatas-celulares-unidimensionales-python", "Autómatas celulares unidimensionales en Python", aarroyoc, "2017-08-28 00:00:00", html("automatas-celulares-unidimensionales-python.html"), public, ["programacion","wolfram","feynman","automatas","matematicas","tutorial","complejidad","teoria-de-juegos","celulares","python"]).
post("premio-nobel-medicina", "Premio Nobel de Medicina", aarroyoc, "2017-10-01 00:00:00", html("premio-nobel-medicina.html"), public, ["mojica","republica","medicina","nobel"]).
post("comienza-la-seminci", "¡Comienza la SEMINCI!", aarroyoc, "2017-10-20 00:00:00", html("comienza-la-seminci.html"), public, ["valladolid","republica","cine","seminci"]).
post("estadistica-python-manipulando-datos-pandas-parte-ii", "Estadística en Python: manipulando datos en Pandas (Parte II)", aarroyoc, "2017-11-01 00:00:00", html("estadistica-python-manipulando-datos-pandas-parte-ii.html"), public, ["big-data","programacion","estadistica","data-science","tutorial","pandas","sql","numpy","python"]).
post("estadistica-python-analisis-datos-multidimensionales-regresion-lineal-parte-iv", "Estadística en Python: análisis de datos multidimensionales y regresión lineal (Parte IV)", aarroyoc, "2017-11-15 00:00:00", html("estadistica-python-analisis-datos-multidimensionales-regresion-lineal-parte-iv.html"), public, ["ley-de-ohm","programacion","regresion-lineal","scipy","estadistica","pearson","tutorial","pandas","numpy","covarianza","fisica","python"]).
post("easter-egg-comando-man-gnu-linux", "Easter egg en el comando man de GNU/Linux", aarroyoc, "2017-11-21 00:00:00", html("easter-egg-comando-man-gnu-linux.html"), public, ["programacion","easter-egg","linux","man","abba"]).
post("programacion-dinamica-el-problema-de-knapsack", "Programación dinámica: el problema de knapsack", aarroyoc, "2018-03-11 00:00:00", html("programacion-dinamica-el-problema-de-knapsack.html"), public, ["programacion","recursividad","knapsack","algoritmos","python"]).
post("juego-la-vida-conway-c-interfaz-grafica", "Juego de la Vida de Conway en C# con interfaz gráfica", aarroyoc, "2018-01-20 00:00:00", html("juego-la-vida-conway-c-interfaz-grafica.html"), public, ["programacion","net","algoritmia","net-core","automatas","quadtree","c","juego-de-la-vida","videojuego","programacion-de-videojuegos","conway","avalonia"]).
post("cheatsheet-de-pandas", "Cheatsheet de Pandas", aarroyoc, "2018-01-19 00:00:00", html("cheatsheet-de-pandas.html"), public, ["big-data","programacion","estadistica","pandas","cheatsheet","python"]).
post("estadistica-python-calculo-probabilidades-parte-v", "Estadística en Python: cálculo de probabilidades (Parte V)", aarroyoc, "2017-12-03 00:00:00", html("estadistica-python-calculo-probabilidades-parte-v.html"), public, ["programacion","bayes","estadistica","probabilidad","python"]).
post("estadistica-python-distribucion-binomial-normal-poisson-parte-vi", "Estadística en Python: distribución binomial, normal y de Poisson (Parte VI)", aarroyoc, "2017-12-08 00:00:00", html("estadistica-python-distribucion-binomial-normal-poisson-parte-vi.html"), public, ["big-data","programacion","scipy","normal","estadistica","probabilidad","tutorial","poisson","python"]).
post("gana-dos-entradas-dobles-bugs-museo-reina-sofia", "Gana dos entradas dobles para \"Bugs\" en el Museo Reina Sofía", aarroyoc, "2017-12-28 00:00:00", html("gana-dos-entradas-dobles-bugs-museo-reina-sofia.html"), public, ["programacion","arte-moderno","javascript","linux","wannacry","efecto-2000","windows","santos-inocentes","lisp","reina-sofia","ariane-5"]).
post("interfaces-graficas-multiplataformas-c-net-core-avalonia", "Interfaces gráficas multiplataforma en C# con .NET Core y Avalonia", aarroyoc, "2017-10-13 00:00:00", html("interfaces-graficas-multiplataformas-c-net-core-avalonia.html"), public, ["gtk","programacion","net","net-core","gui","c","xaml","avalonia"]).
post("leer-escribir-json-rust-serde", "Leer y escribir JSON en Rust con Serde", aarroyoc, "2017-12-30 00:00:00", html("leer-escribir-json-rust-serde.html"), public, ["programacion","serde","linux","rust","tutorial","json"]).
post("yew-frontend-rust-angular-react", "Yew, crea webapps al estilo Angular/React en Rust", aarroyoc, "2018-01-01 00:00:00", html("yew-frontend-rust-angular-react.html"), public, ["programacion","yew","webassembly","linux","rust","tutorial","elm","web-framework","emscripten","web"]).
post("funcionan-meltdown-spectre-explicado-instastories", "¿Cómo funcionan Meltdown y Spectre? Explicado con InstaStories", aarroyoc, "2018-01-05 00:00:00", html("funcionan-meltdown-spectre-explicado-instastories.html"), public, ["programacion","linux","ciberseguridad","meltdown","vulnerabilidad","spectre"]).
post("como-aumente-visitas-blog", "¿Cómo aumenté las visitas a mi blog?", aarroyoc, "2017-11-02 00:00:00", html("como-aumente-visitas-blog.html"), public, ["analiticas","meta","analisis","republica","blog"]).
post("estadisticas-blog-2017", "Estadísticas del blog, versión 2017", aarroyoc, "2017-12-10 00:00:00", html("estadisticas-blog-2017.html"), public, ["estadistica","2017","trafico-web","analytics","analisis","republica","web"]).
post("monada-st-en-haskell-stref-starray", "Mónada ST en Haskell: STRef, STArray", aarroyoc, "2018-04-09 00:00:00", html("monada-st-en-haskell-stref-starray.html"), public, ["programacion","st","funcional","monada","haskell","bubblesort"]).
post("que-nos-espera-en-haiku-beta", "¿Qué nos espera en Haiku Beta?", aarroyoc, "2014-11-17 00:00:00", html("que-nos-espera-en-haiku-beta.html"), public, ["programacion","sistemas-operativos","haiku"]).
post("un-muro-en-cuzco", "Un muro en Cuzco", aarroyoc, "2018-04-04 00:00:00", html("un-muro-en-cuzco.html"), public, ["mentalidad","relativismo","prioridades","filosofia","inca","espana","religion-y-filosofia"]).
post("introduccion-a-prolog-tutorial-en-espanol", "Introducción a Prolog, tutorial en español", aarroyoc, "2018-04-12 00:00:00", html("introduccion-a-prolog-tutorial-en-espanol.html"), public, ["programacion","prolog","predicados","linux","tutorial","programacion-logica","unificacion","logica"]).
post("tutorial-introduccion-godot-3-0-juego-snake-c", "Tutorial de introducción a Godot 3.0. Juego de Snake en C#", aarroyoc, "2018-01-30 00:00:00", html("tutorial-introduccion-godot-3-0-juego-snake-c.html"), public, ["programacion","net","c","mono","programacion-de-videojuegos","videojuegos","godot"]).
post("recuperar-archivos-borrados", "¿Cómo recuperar archivos borrados?", aarroyoc, "2018-02-02 00:00:00", html("recuperar-archivos-borrados.html"), public, ["recuva","republica","disco-duro","recuperar"]).
post("te-espero-la-feria-espacios-ingenio", "Te espero en la feria Espacios de Ingenio", aarroyoc, "2018-02-21 00:00:00", html("te-espero-la-feria-espacios-ingenio.html"), public, ["valladolid","republica","python"]).
post("futures-tokio-programar-forma-asincrona-rust", "Futures y Tokio: programar de forma asíncrona en Rust", aarroyoc, "2018-02-23 00:00:00", html("futures-tokio-programar-forma-asincrona-rust.html"), public, ["futures","futuros","programacion","tokio","linux","rust","tutorial","asincrono","tcp"]).
post("como-funcionan-los-sistemas-de-archivos-basados-en-fat", "¿Cómo funcionan los sistemas de archivos basados en FAT?", aarroyoc, "2018-06-11 00:00:00", html("como-funcionan-los-sistemas-de-archivos-basados-en-fat.html"), public, ["sistemas-operativos","programacion","sistemas-de-archivos","fat","linux"]).
post("advent-of-code-2018-primera-semana", "Advent of Code 2018: primera semana", aarroyoc, "2018-12-07 00:00:00", html("advent-of-code-2018-primera-semana.html"), public, ["programacion","advent-of-code","algoritmia","algoritmos","python"]).
post("fabric-automatiza-tareas-en-remoto", "Fabric, automatiza tareas en remoto", aarroyoc, "2018-05-19 00:00:00", html("fabric-automatiza-tareas-en-remoto.html"), public, ["sysadmin","programacion","fabric","server","ssh","tutorial","devops","python"]).
post("ayuda-a-la-ciencia-desde-tu-casa-con-boinc", "Ayuda a la ciencia desde tu casa con BOINC", aarroyoc, "2018-05-26 00:00:00", html("ayuda-a-la-ciencia-desde-tu-casa-con-boinc.html"), public, ["boinc","programacion","superordenador","sistemas-distribuidos","seti","lhc"]).
post("bindings-rust-c-bindgen", "Bindings entre Rust y C/C++ con bindgen", aarroyoc, "2018-06-07 00:00:00", html("bindings-rust-c-bindgen.html"), public, ["programacion","linux","rust","c","bindgen","sqlite","cpp","tutorial","cargo"]).
post("la-perlificacion-de-python", "La perlificación de Python", aarroyoc, "2018-07-10 00:00:00", html("la-perlificacion-de-python.html"), public, ["programacion","linux","c","barroco","perl","reflexion","python"]).
post("emulando-linus-torvalds-crea-propio-sistema-operativo-desde-0-vi", "Emulando a Linus Torvalds: Crea tu propio sistema operativo desde 0 (VI)", aarroyoc, "2015-12-01 00:00:00", html("emulando-linus-torvalds-crea-propio-sistema-operativo-desde-0-vi.html"), public, ["isr","programacion","sistemas-operativos","interrupt","kernel","exception","linux","irq","next-divel"]).
post("computacion-cuantica-para-torpes-introduccion-para-programadores", "Computación cuántica para torpes: introducción para programadores", aarroyoc, "2018-07-17 00:00:00", html("computacion-cuantica-para-torpes-introduccion-para-programadores.html"), public, ["programacion","ibm-q","q","tutorial","computacion-cuantica","introduccion","ordenadores-cuanticos","fisica"]).
post("lista-sponsors-juegos-html5", "Lista de sponsors para juegos HTML5", aarroyoc, "2015-08-15 00:00:00", html("lista-sponsors-juegos-html5.html"), public, ["programacion","lista","marketing","sponsors","programacion-de-videojuegos","dinero","html5"]).
post("acortar-enlaces-node-js", "Acortar enlaces en Node.js", aarroyoc, "2015-10-31 00:00:00", html("acortar-enlaces-node-js.html"), public, ["programacion","ganar","javascript","enlaces","acortadores","dinero","nodejs"]).
post("redox-sistema-operativo-escrito-rust", "Redox, el sistema operativo escrito en Rust", aarroyoc, "2015-11-01 00:00:00", html("redox-sistema-operativo-escrito-rust.html"), public, ["sistemas-operativos","programacion","rust","redox"]).
post("emulando-linus-torvalds-crea-propio-sistema-operativo-desde-0-viii", "Emulando a Linus Torvalds: Crea tu propio sistema operativo desde 0 (VIII)", aarroyoc, "2015-12-03 00:00:00", html("emulando-linus-torvalds-crea-propio-sistema-operativo-desde-0-viii.html"), public, ["programacion","sistemas-operativos","teclado","x86","kernel","linux","next-divel","keymap"]).
post("tutorial-rocket-echa-volar-tus-webapps-rust", "Tutorial de Rocket, echa a volar tus webapps con Rust", aarroyoc, "2017-04-15 00:00:00", html("tutorial-rocket-echa-volar-tus-webapps-rust.html"), public, ["programacion","http","linux","rust","tutorial","rocket","web-framework","web"]).
post("box-rc-refcell-punteros-inteligentes-rust", "Box, Rc y RefCell, punteros inteligentes en Rust", aarroyoc, "2017-07-03 00:00:00", html("box-rc-refcell-punteros-inteligentes-rust.html"), public, ["programacion","rc","rust","tutorial","box","refcell"]).
post("crear-ventanas-botones-rust-gtk", "Crear ventanas y botones en Rust con GTK", aarroyoc, "2017-09-29 00:00:00", html("crear-ventanas-botones-rust-gtk.html"), public, ["gtk","programacion","gui","linux","rust","tutorial","ventana","boton"]).
post("curve-una-tarjeta-dominarlas-todas", "Curve, una tarjeta para dominarlas a todas", aarroyoc, "2017-11-24 00:00:00", html("curve-una-tarjeta-dominarlas-todas.html"), public, ["n26","tarjetas","republica","emv","revolut","nfc","curve"]).
post("consejo-escolar", "Consejo Escolar", aarroyoc, "2012-11-20 00:00:00", html("consejo-escolar.html"), public, ["republica"]).
post("tutorial-couchdb", "Tutorial de CouchDB", aarroyoc, "2017-06-15 00:00:00", html("tutorial-couchdb.html"), public, ["ssl","programacion","erlang","http","base-de-datos","javascript","rest","tutorial","bbdd","couchdb","map-reduce","nosql","json","cors"]).
post("los-navegadores-del-2012", "Los navegadores del 2012", aarroyoc, "2012-12-29 00:00:00", html("los-navegadores-del-2012.html"), public, ["republica"]).
post("feliz-navidad-2018", "Feliz Navidad 2018", aarroyoc, "2018-12-25 00:00:00", html("feliz-navidad-2018.html"), public, ["webs","estadistica","trafico-web","republica","navidad"]).
post("los-numeros-aleatorios", "Los números aleatorios", aarroyoc, "2013-03-11 00:00:00", html("los-numeros-aleatorios.html"), public, ["republica"]).
post("las-mejores-librerias-gratuitas-para-graficas-en-php", "Las mejores librerías gratuitas para gráficas en PHP", aarroyoc, "2018-12-15 00:00:00", html("las-mejores-librerias-gratuitas-para-graficas-en-php.html"), public, ["programacion","estadistica","graficas","d3","php"]).
post("phaser-js-hispano-aprende-videojuegos-html5", "Phaser.js Hispano, aprende a hacer videojuegos en HTML5", aarroyoc, "2016-09-01 00:00:00", html("phaser-js-hispano-aprende-videojuegos-html5.html"), public, ["programacion","webgl","javascript","motor","tutorial","videojuego","canvas","programacion-de-videojuegos","phaser","2d","html5"]).
post("como-borrar-el-historial", "¿Cómo borrar el historial?", aarroyoc, "2017-02-15 00:00:00", html("como-borrar-el-historial.html"), public, ["historial","firefox","borrar","republica","cookies","web"]).
post("cargo-modulos-rust", "Cargo y módulos en Rust", aarroyoc, "2017-07-03 00:00:00", html("cargo-modulos-rust.html"), public, ["programacion","modulo","rust","tutorial","crate","cargo"]).
post("lenguajes-programacion-buen-programador-conocer", "Lenguajes de programación que todo buen programador debe conocer", aarroyoc, "2018-02-18 00:00:00", html("lenguajes-programacion-buen-programador-conocer.html"), public, ["programacion","prolog","racket","javascript","linux","rust","c","programacion-orientada-a-objetos","haskell","python"]).
post("cronica-neuronal-house-prices", "Crónica Neuronal: House Prices", aarroyoc, "2019-08-04 16:10:41.396312", html("cronica-neuronal-house-prices.html"), public, ["programacion","cronica neuronal","machine learning","tutorial","inteligencia artificial","kaggle","big data","ia"]).
post("teletexto-002", "Teletexto #002", aarroyoc, "2020-01-19 20:12:38.625269", html("teletexto-002.html"), public, ["programacion","falacias","sms","dgraph","bazaar","rust","sql","teletexto","git","devops","filosofia","breezy"]).
post("cronica-neuronal-indian-liver-patients-record", "Crónica Neuronal: Indian Liver Patients Record", aarroyoc, "2019-08-06 21:34:07.651397", html("cronica-neuronal-indian-liver-patients-record.html"), public, ["programacion","cronica neuronal","machine learning","tutorial","inteligencia artificial","kaggle","big data","ia"]).
post("servidor-webdav-nginx", "Servidor WebDAV con nginx", aarroyoc, "2019-08-08 16:12:28.649257", html("servidor-webdav-nginx.html"), public, ["nginx","programacion","webdav","tutorial","s3"]).
post("videojuegos-verano-ordenador", "Videojuegos de ordenador para el verano", aarroyoc, "2019-08-10 17:24:35.663163", html("videojuegos-verano-ordenador.html"), public, ["ordenadores","videojuegos","gaming"]).
post("jq-sed-siglo-xxi", "jq, el sed del siglo XXI", aarroyoc, "2019-08-12 17:38:16.004727", html("jq-sed-siglo-xxi.html"), public, ["programacion","linux","tutorial","awk","jq","sed","json"]).
post("podcast-docker", "Podcast sobre Docker", aarroyoc, "2019-08-19 17:23:28.330812", html("podcast-docker.html"), public, ["programacion","audio","linux","devops","docker","podcast"]).
post("rust-no-es-buen-reemplazo-c", "Re: Rust no es un buen reemplazo de C", aarroyoc, "2019-08-17 12:11:13.144708", html("rust-no-es-buen-reemplazo-c.html"), public, ["correo","programacion","rust","c"]).
post("tu-codigo-va-a-morir", "Tu código va a morir", aarroyoc, "2019-09-25 15:41:29.741139", html("tu-codigo-va-a-morir.html"), public, ["programacion","filosofia","reflexion"]).
post("terraform-cloud-declarativa", "Terraform, infraestructura como código declarativo", aarroyoc, "2019-09-17 20:38:10.975976", html("terraform-cloud-declarativa.html"), public, ["programacion","terraform","tutorial","declarativa"]).
post("cronica-neuornal-matrices-expresion-genetica-leucemia", "Crónica Neuronal: matrices de expresión genética para leucemia", aarroyoc, "2019-10-21 22:33:58.553361", html("cronica-neuornal-matrices-expresion-genetica-leucemia.html"), public, ["programacion","biologia"," leucemia"," genetica","bioinformatica","inteligencia artificial","cronica","neuronal"]).
post("linux-tapas-web-30-redes-descentralizadas", "Ponencia Linux y Tapas 2019: \"Web 3 0: redes descentralizadas\"", aarroyoc, "2019-11-01 16:54:42.452301", html("linux-tapas-web-30-redes-descentralizadas.html"), public, ["zeronet","programacion","dat","ipfs","leon","ponencia","presentacion","linuxytapas"]).
post("problemas-nix", "Problemas de Nix", aarroyoc, "2020-01-31 19:23:19.050808", html("problemas-nix.html"), public, ["programacion","linux","tutorial","nix"]).
post("historia-privacidad", "Historia de la privacidad", aarroyoc, "2019-11-24 23:28:42.282811", html("historia-privacidad.html"), public, ["programacion","historia","filosofia","privacidad"]).
post("ley-zipf-blog", "Ley de Zipf en el blog", aarroyoc, "2019-11-25 21:47:21.440312", html("ley-zipf-blog.html"), public, ["zipf","ley","blog","estadistica"]).
post("yield-generadores-python", "Yield, generadores y corrutinas en Python", aarroyoc, "2019-12-27 16:19:59.277153", html("yield-generadores-python.html"), public, ["programacion","generadores","tutorial","yield","python"]).
post("prolog-dcg-gramaticas-clausula-definida", "Prolog DCG: gramáticas de clausula definida", aarroyoc, "2020-01-14 13:02:47.323952", html("prolog-dcg-gramaticas-clausula-definida.html"), public, ["prolog","programacion","gramaticas","tutorial","dcg","lenguages","compilador","logica"]).
post("diesel-orm-rust", "Diesel, un ORM para Rust", aarroyoc, "2020-01-03 15:43:12.209853", html("diesel-orm-rust.html"), public, ["programacion","rust","tutorial","sql","orm"]).
post("universo-prolog", "El Universo Prolog", aarroyoc, "2020-04-30 21:02:11.11248", html("universo-prolog.html"), public, ["prolog","programacion","linux","swi-prolog"]).
post("feliz-2020", "¡Feliz año 2020!", aarroyoc, "2019-12-31 19:48:00.511483", html("feliz-2020.html"), public, ["felicitacion","blog","estadistica"]).
post("teletexto-001", "Teletexto #001", aarroyoc, "2020-01-08 14:08:41.104482", html("teletexto-001.html"), public, ["alpine","programacion","prolog","django","postgres","teletexto","haskell","sklearn"]).
post("agromapa-castilla-leon", "Agromapa de Castilla y León", aarroyoc, "2019-04-08 16:43:13.812658", html("agromapa-castilla-leon.html"), public, ["programacion","castilla","datos abiertos","open data","visualizacion","premio","concurso","mapa"]).
post("primeros-pasos-nix-linux-funcional", "Primeros pasos con Nix: un Linux más funcional", aarroyoc, "2020-01-25 19:36:28.615868", html("primeros-pasos-nix-linux-funcional.html"), public, ["nixos","programacion","linux","tutorial","nix","debian","python"]).
post("teletexto-003", "Teletexto #003", aarroyoc, "2020-02-09 12:16:48.224946", html("teletexto-003.html"), public, ["programacion","mapas","trident","ruby","pandas","css","teletexto","spotify","gnome","web"]).
post("desplegar-web-estatica-github-netlify", "Desplegar una página estática con GitHub Actions y Netlify", aarroyoc, "2020-01-31 20:15:40.485082", html("desplegar-web-estatica-github-netlify.html"), public, ["programacion","linux","tutorial","github","netlify","lektor","docker","web"]).
post("programacion-lineal-alcanzar-perfeccion", "Programación lineal: alcanzando la perfección", aarroyoc, "2019-04-14 23:29:06.94412", html("programacion-lineal-alcanzar-perfeccion.html"), public, ["programacion","prolog","matematicas","programacion lineal","tutorial","optimizacion"]).
post("testing-lenguaje-natural-behave-python", "Testing en lenguaje natural con Gherkin y Behave", aarroyoc, "2020-02-20 17:05:26.72458", html("testing-lenguaje-natural-behave-python.html"), public, ["programacion","testing","linux","tutorial","behave","bdd","python"]).
post("teletexto-004", "Teletexto #004", aarroyoc, "2020-03-03 22:33:44.632955", html("teletexto-004.html"), public, ["programacion","javascript","ai","ciberseguridad","kaggle","teletexto","darcs"]).
post("rustizando-linux", "Rustizando tu Linux", aarroyoc, "2020-03-17 14:36:18.062695", html("rustizando-linux.html"), public, ["programacion","linux","rust","tutorial","exa","cli","nushell"]).
post("estadistica-python", "Estadística en Python", aarroyoc, "2020-03-17 15:55:11.616216", html("estadistica-python.html"), public, ["python","programacion","estadistica"]).
post("teletexto-005", "Teletexto #005", aarroyoc, "2020-03-30 21:56:18.607173", html("teletexto-005.html"), public, ["programacion","prolog","javascript","pijul","teletexto","ogg","spark","machine-learning","python"]).
post("sudoku-prolog", "Sudoku en Prolog", aarroyoc, "2020-04-12 22:19:57.52384", html("sudoku-prolog.html"), public, ["prolog","programacion","linux","sudoku"]).
post("debug-grafico-prolog", "Debug gráfico en Prolog", aarroyoc, "2020-04-16 21:18:22.779534", html("debug-grafico-prolog.html"), public, ["prolog","programacion","linux","debug"]).
post("construye-renault-4", "Construye un Renault 4", aarroyoc, "2020-04-25 20:39:22.678081", html("construye-renault-4.html"), public, ["programacion","ensayo","filosofia","motivacion"]).
post("teletexto-006", "Teletexto #006", aarroyoc, "2020-05-13 18:52:54.689803", html("teletexto-006.html"), public, ["programacion","javascript","rust","teletexto","postgresql","cobol","kubernetes","python"]).
post("agregador-enlaces-aws-lambda-terraform", "Agregador de enlaces en la nube con AWS Lambda y Terraform", aarroyoc, "2020-05-26 15:45:20.654663", html("agregador-enlaces-aws-lambda-terraform.html"), public, ["programacion","terraform","python","linux","aws","lambda"]).
post("regex-torpes", "Regex para torpes", aarroyoc, "2020-07-26 18:51:55.860717", html("regex-torpes.html"), public, ["programacion","linux","rust","regex","python"]).
post("teletexto-007", "Teletexto #007", aarroyoc, "2020-08-15 22:36:28.349756", html("teletexto-007.html"), public, ["idris","programacion","unix","oxigraph","questdb","css","teletexto","soft skills"]).
post("algoritmo-simplex", "El Algoritmo Simplex", aarroyoc, "2020-09-12 20:10:22.810959", html("algoritmo-simplex.html"), public, ["programacion","rust","tutorial","investigacion operativa","simplex"]).
post("mapaquiz-pregunta-sobre-mapa", "Mapaquiz, ¿y si la respuesta estuviera sobre el mapa?", aarroyoc, "2020-10-30 19:26:21.86428", html("mapaquiz-pregunta-sobre-mapa.html"), public, ["programacion","django","mapas","mapaquiz","python"]).
post("que-es-idris-y-por-que-es-un-lenguaje-de-programacion-tan-interesante", "¿Qué es Idris y por qué es un lenguaje de programación tan interesante?", aarroyoc, "2020-09-27 22:31:38.258232", html("que-es-idris-y-por-que-es-un-lenguaje-de-programacion-tan-interesante.html"), public, ["idris","programacion","linux","tutorial","haskell"]).
post("supertutorial-prolog", "Supertutorial de Prolog: aprende Prolog en español", aarroyoc, "2020-08-29 09:37:47.560059", html("supertutorial-prolog.html"), public, ["prolog","programacion","tutorial"]).
post("estadisticas-2020", "Estadísticas y felicitaciones de 2020", aarroyoc, "2021-01-01 17:09:54.85717", html("estadisticas-2020.html"), public, ["felicitacion","blog","estadistica"]).
post("teletexto-008", "Teletexto #008", aarroyoc, "2020-11-07 16:14:43.412973", html("teletexto-008.html"), public, ["quel","programacion","map","rust","vega","sql","teletexto","posix","mozilla"]).
post("tutorial-chr", "Tutorial de CHR (Constraint Handling Rules)", aarroyoc, "2020-11-18 21:38:35.807372", html("tutorial-chr.html"), public, ["prolog","programacion","linux","tutorial","chr"]).
post("space-pipes", "Space Pipes", aarroyoc, "2020-11-22 16:25:17.133522", html("space-pipes.html"), public, ["prolog","programacion","android","typescript","space-pipes"]).
post("nuevos-horizontes-pfizer", "Nuevos horizontes (Pfizer)", aarroyoc, "2020-12-28 21:21:12.80626", html("nuevos-horizontes-pfizer.html"), public, ["inocentada","broma"]).
post("easter-egg-python", "Easter eggs en Python", aarroyoc, "2021-01-10 17:16:31.897094", html("easter-egg-python.html"), public, ["easter egg","programacion","linux","tutorial","python"]).
post("tipos-suma-typescript-rust", "¿Qué son los tipos suma? Explicación en TypeScript y Rust", aarroyoc, "2021-01-10 22:26:24.631087", html("tipos-suma-typescript-rust.html"), public, ["programacion","rust","tutorial","sum types","typescript"]).
post("formato-ron-rusty-object-notation", "El formato RON: Rusty Object Notation", aarroyoc, "2021-02-06 12:02:14.380039", html("formato-ron-rusty-object-notation.html"), public, ["programacion","serde","linux","rust","tutorial","ron"]).
post("teletexto-009", "Teletexto #009", aarroyoc, "2021-02-28 17:16:18.372128", html("teletexto-009.html"), public, ["programacion","prolog","sistemas operativos","ecs","rust","ensamblador","teletexto","debian","godot","python"]).
post("buscando-facebook-leak-elasticsearch", "Buscando en los datos del leak de Facebook con ElasticSearch", aarroyoc, "2021-04-07 20:15:14.759734", html("buscando-facebook-leak-elasticsearch.html"), public, ["programacion","python","kibana","tutorial","leak","logstash","elasticsearch","facebook"]).
post("soccerdoku-prolog-clpz", "Soccerdoku en Prolog (usando clpz)", aarroyoc, "2021-06-13 21:32:16.839609", html("soccerdoku-prolog-clpz.html"), public, ["prolog","programacion","linux","tutorial","soccerdoku","clpz"]).
post("llamar-rust-prolog-swipl-rs", "Llamar a Rust desde Prolog: swipl-rs", aarroyoc, "2021-05-31 22:08:48.395207", html("llamar-rust-prolog-swipl-rs.html"), public, ["prolog","programacion","rust","tutorial","raylib"]).
post("teletexto-010", "Teletexto #010", aarroyoc, "2021-06-01 18:57:34.088197", html("teletexto-010.html"), public, ["programacion","europa","mapas","java","teletexto","gis","ovni","avion"]).
post("usar-la-vulnerabilidad-dirtycow-convertirse-root-linux", "Usar la vulnerabilidad DirtyCoW para convertirse en root en Linux", aarroyoc, "2016-11-05 00:00:00", html("usar-la-vulnerabilidad-dirtycow-convertirse-root-linux.html"), public, ["programacion","root","dirtycow","linux","tutorial","exploit","vulnerabilidad","seguridad"]).
post("reinforcement-learning-aprendizaje-refuerzo-mdp-bellman-2", "Reinforcement Learning (Aprendizaje por refuerzo): MDPs y ecuación de Bellman", aarroyoc, "2021-08-05 22:03:36.168822", html("reinforcement-learning-aprendizaje-refuerzo-mdp-bellman-2.html"), public, ["programacion","aprendizaje refuerzo","matematicas","machine learning","tutorial","markov"]).
post("reinforcement-learning-aprendizaje-refuerzo-q-learning-3", "Reinforcement Learning (Aprendizaje por refuerzo): Q-Learning (parte 3)", aarroyoc, "2021-08-18 20:38:19.198255", html("reinforcement-learning-aprendizaje-refuerzo-q-learning-3.html"), public, ["programacion","mdp","tutorial","inteligencia artificial","reinforcement learning","q learning","python"]).
post("reinforcement-learning-aprendizaje-refuerzo-que-es-parte-1", "Reinforcement Learning (Aprendizaje por refuerzo): ¿Qué es y cómo funciona? (parte 1)", aarroyoc, "2021-08-04 21:55:09.499915", html("reinforcement-learning-aprendizaje-refuerzo-que-es-parte-1.html"), public, ["programacion","aprendizaje refuerzo","matematicas","machine learning","tutorial"]).
post("reinforcement-learning-aprendizaje-refuerzo-dqn-openai-gym-stable-baselines-4", "Reinforcement Learning (Aprendizaje por refuerzo): DQN, OpenAI Gym, Stable Baselines (parte 4)", aarroyoc, "2021-09-05 10:32:37.196283", html("reinforcement-learning-aprendizaje-refuerzo-dqn-openai-gym-stable-baselines-4.html"), public, ["programacion","aprendizaje refuerzo","dqn","openai gym","stable baselines","tutorial"]).
post("teletexto-011", "Teletexto #011", aarroyoc, "2021-11-02 21:53:41.847468", html("teletexto-011.html"), public, ["programacion","gamedev","testing","javascript","java","teletexto","minikanren","python"]).
post("rutaxrutaxcyl", "Ruta x ruta x Castilla y León", aarroyoc, "2021-11-08 21:57:43.334594", html("rutaxrutaxcyl.html"), public, ["programacion","kotlin","datos abiertos","mapas","memoria","premio","concurso"]).
post("herramientas-empezar-big-data", " Herramientas para empezar con Big Data ", aarroyoc, "2021-11-30 23:50:52.732654", html("herramientas-empezar-big-data.html"), public, ["programacion","d3","sql","big data","spark"]).
post("problema-hello-world", "El problema del Hello World", aarroyoc, "2021-12-13 23:05:24.722708", html("problema-hello-world.html"), public, ["prolog","programacion","javascript","rust","opinion","haskell","hello world"]).
post("htmx-html-hipertexto-en-serio", "htmx, o como sería HTML si se tomase el hipertexto en serio", aarroyoc, "2021-12-21 19:58:48.812399", html("htmx-html-hipertexto-en-serio.html"), public, ["programacion","javascript","htmx","tutorial","html","web"]).
post("introduccion-z3-demostrador-teoremas", "Introducción a Z3, el demostrador de teoremas de Microsoft", aarroyoc, "2021-12-29 23:28:08.189284", html("introduccion-z3-demostrador-teoremas.html"), public, ["prolog","programacion","sudoku","tutorial","z3","python"]).
post("sorteo-2022-que-has-aprendido-blog", "Sorteo 2022: ¿Qué has aprendido en el blog?", aarroyoc, "2021-12-30 21:44:34.676902", html("sorteo-2022-que-has-aprendido-blog.html"), public, ["concurso","felicitacion"]).
post("alien-fingers-prolog", "Alien fingers en Prolog", aarroyoc, "2022-01-28 17:09:42.145178", html("alien-fingers-prolog.html"), public, ["prolog","programacion","puzzle","tutorial","problema","dcg"]).
post("logtalk-prolog-orientado-objetos", "Logtalk, Prolog orientado a objetos", aarroyoc, "2022-02-17 22:41:25.694544", html("logtalk-prolog-orientado-objetos.html"), public, ["prolog","programacion","logtalk","tutorial"]).
post("codigo-morse-prolog", "Código Morse en Prolog", aarroyoc, "2022-03-11 10:42:46.761386", html("codigo-morse-prolog.html"), public, ["prolog","programacion","morse","tutorial","dcg","scryer"]).
post("teletexto-012", "Teletexto #012", aarroyoc, "2022-04-03 15:37:54.767816", html("teletexto-012.html"), public, ["programacion","prolog","gamedev","clojure","kotlin","gradle","concurrencia","apl","teletexto","z3","matrix"]).
post("planificar-scuba-prolog", "Planificar una inmersión SCUBA con Prolog", aarroyoc, "2022-08-20 21:50:43.428353", html("planificar-scuba-prolog.html"), public, ["prolog","programacion","tutorial","scuba"]).
post("mercury-prolog-haskell-bebe", "Mercury: cuando Prolog y Haskell tuvieron un bebé", aarroyoc, "2022-04-17 10:40:02.714386", html("mercury-prolog-haskell-bebe.html"), public, ["prolog","programacion","mercury","tutorial"]).
post("resolviendo-3-jarras-jugs-automaton-clpz", "Resolviendo el problema de las 3 jarras usando automaton y clpz", aarroyoc, "2022-06-19 16:27:42.500392", html("resolviendo-3-jarras-jugs-automaton-clpz.html"), public, ["prolog","programacion","automatas","puzzle","tutorial","clpz"]).
post("usando-lenguaje-mejor-pagado-clojure", "Usando el lenguaje mejor pagado del mundo: Clojure", aarroyoc, "2022-08-14 12:34:39.470971", html("usando-lenguaje-mejor-pagado-clojure.html"), public, ["programacion","clojure","tutorial","jvm","java","lisp","calculadora","rpn"]).
post("paseo-ensamblador-risc-v-64", "Un paseo por el ensamblador de RISC-V", aarroyoc, "2022-08-23 21:03:36.698186", html("paseo-ensamblador-risc-v-64.html"), public, ["programacion","tutorial","riscv","ensamblador","risc"]).
post("acertijo-cebra", "El acertijo de la cebra", aarroyoc, "2022-11-06 17:10:59.096336", html("acertijo-cebra.html"), public, ["prolog","programacion","puzzle","tutorial","acertijo","clpz"]).
post("clips-motor-reglas-nasa", "CLIPS: el motor de reglas de la NASA", aarroyoc, "2022-10-27 20:53:50.367204", html("clips-motor-reglas-nasa.html"), public, ["prolog","programacion","tutorial","lisp","clips","logica"]).
post("wc-en-prolog", "Comando wc en Prolog", aarroyoc, "2022-11-19 16:45:44.164238", html("wc-en-prolog.html"), public, ["prolog","programacion","wc","unix","tutorial","dcg"]).
post("famoso-problema-15-puzzle", "El famoso problema del 15-puzzle en Prolog", aarroyoc, "2022-06-11 22:59:38.462985", html("famoso-problema-15-puzzle.html"), public, ["prolog","programacion","heuristica","puzzle","tutorial"]).
post("optimizar-mudanza-proyecto-software-prolog", "Optimizar una mudanza (o un proyecto de software) en Prolog", aarroyoc, "2022-11-22 20:27:13.904485", html("optimizar-mudanza-proyecto-software-prolog.html"), public, ["prolog","programacion","tutorial","mudanza","clpz"]).
post("camino-a-prolog-unificacion", "El camino a Prolog: unificación (parte I)", aarroyoc, "2022-12-27 20:05:23.200494", html("camino-a-prolog-unificacion.html"), public, ["prolog","programacion","rust","tutorial","unificacion"]).
post("camino-a-prolog-repl", "El camino a Prolog: parser y juntarlo todo (parte III)", aarroyoc, "2023-01-02 14:45:51.569174", html("camino-a-prolog-repl.html"), public, ["prolog","programacion","tutorial","repl","zebra"]).
post("strand-lenguaje-extremadamente-paralelo", "Strand, un lenguaje extremadamente paralelo", aarroyoc, "2023-01-15 17:33:06.992869", html("strand-lenguaje-extremadamente-paralelo.html"), public, ["prolog","programacion","paralelismo","tutorial","fleng","concurrencia","strand"]).
post("just-sustituto-make-polivalente", "Just, un sustituto de Make polivalente", aarroyoc, "2023-04-23 10:37:00.134824", html("just-sustituto-make-polivalente.html"), public, ["just","programacion","linux","tutorial","make"]).
post("usando-nixos-servidor-raspberry", "Usando NixOS como servidor en una Raspberry Pi", aarroyoc, "2023-03-06 19:09:03.450055", html("usando-nixos-servidor-raspberry.html"), public, ["nixos","nginx","programacion","arm","raspberry","linux","tutorial","nix","docker"]).
post("bqn-programacion-basada-arrays", "BQN: programación basada en arrays", aarroyoc, "2023-04-16 15:13:11.515573", html("bqn-programacion-basada-arrays.html"), public, ["programacion","array","tutorial","apl","bqn"]).
post("sustituyendo-google-photos-solucion-local", "Sustituyendo Google Photos por mi propia solución local", aarroyoc, "2023-05-28 11:53:53.28929", html("sustituyendo-google-photos-solucion-local.html"), public, ["programacion","borg","syncthing","linux","tutorial","photos"]).
post("que-necesita-buen-protector-pantalla-movil", "¿Qué necesita tener un buen protector de pantalla de móvil?", aarroyoc, "2023-06-14 21:05:35.415432", html("que-necesita-buen-protector-pantalla-movil.html"), public, ["accesorios","moviles","protector pantalla"]).
post("transcripcion-las-inteligencias-artificiales-tienen-derechos-ernesto-castro", "\"¿Las inteligencias artificiales tienen derechos?\" transcripción de Ernesto Castro", aarroyoc, "2023-04-22 18:21:04.408261", html("transcripcion-las-inteligencias-artificiales-tienen-derechos-ernesto-castro.html"), public, ["programacion","openai","ernesto castro","charla","ia","filosofia","python"]).
post("podemos-perder-tecnologia", "¿Podemos perder tecnología?", aarroyoc, "2023-07-22 10:47:08.242111", html("podemos-perder-tecnologia.html"), public, ["historia","tecnologia","ensayo"]).
post("can-we-lose-technology", "Can we lose technology?", aarroyoc, "2023-07-22 13:36:41.783263", html("can-we-lose-technology.html"), public, ["historia","tecnologia","ensayo"]).
post("introduccion-apache-spark", "Introducción a Apache Spark con datos de la Fórmula 1", aarroyoc, "2023-11-27 22:23:07.758107", html("introduccion-apache-spark.html"), public, ["programacion","scala","tutorial","sql","java","big data","spark"]).
post("scryer-prolog-meetup-2023-notes-day2", "Scryer Prolog Meetup 2023 Notes (day 2)", aarroyoc, "2023-11-14 17:19:36.375494", html("scryer-prolog-meetup-2023-notes-day2.html"), public, ["scryer","prolog","meetup","notes"]).
post("scryer-prolog-meetup-2023-notes", "Scryer Prolog Meetup 2023 Notes", aarroyoc, "2023-11-14 17:18:07.528138", html("scryer-prolog-meetup-2023-notes.html"), public, ["scryer","prolog","meetup","notes"]).
post("ejecutar-maquina-virtual-mips-risc-v-powerpc-sparc", "Ejecutar una máquina virtual RISC-V, MIPS, PowerPC, SPARC,... desde AMD64", aarroyoc, "2024-03-28 23:48:26.964447", html("ejecutar-maquina-virtual-mips-risc-v-powerpc-sparc.html"), public, ["programacion","linux","risc-v","tutorial","debian","qemu","mips"]).
post("video-charla-strand", "Vídeo de mi charla de Strand", aarroyoc, "2023-12-18 19:57:00.026543", html("video-charla-strand.html"), public, ["programacion","prolog","paralelismo","tutorial","strand","video"]).
post("videojuegos-2023", "Videojuegos en 2023", aarroyoc, "2023-12-28 15:07:35.909045", html("videojuegos-2023.html"), public, ["critica","recapitulacion","videojuegos"]).
post("diversion-shaders-wgsl", "Diversión con shaders en WGSL", aarroyoc, "2024-01-18 22:17:23.648498", html("diversion-shaders-wgsl.html"), public, ["gpu","programacion","shaders","wgsl","bevy","rust","tutorial"]).
post("curva-hilbert-prolog", "Curva de Hilbert en Prolog", aarroyoc, "2024-01-30 22:05:15.953392", html("curva-hilbert-prolog.html"), public, ["fractal","prolog","programacion","dcgs","tutorial","svg"]).
post("pascal-homenaje-niklaus-wirth", "Pascal. Un homenaje a Niklaus Wirth", aarroyoc, "2024-02-07 19:08:08.460529", html("pascal-homenaje-niklaus-wirth.html"), public, ["pascal","programacion","wirth","tutorial"]).
post("nuevas-charlas-ppt-adrianistan-eu", "Nuevas charlas en ppt.adrianistan.eu", aarroyoc, "2024-06-28 16:10:03.041262", html("nuevas-charlas-ppt-adrianistan-eu.html"), public, ["prolog","programacion","kotlin","openstreetmap","charlas","strand","spark","wikipedia"]).
post("blogs-cada-vez-mas-importantes-no-menos", "Los blogs cada vez son más importantes, no menos", aarroyoc, "2024-02-08 20:52:14.58254", html("blogs-cada-vez-mas-importantes-no-menos.html"), public, ["ensayo","blogs","chatgpt"]).
post("instalando-gentoo-orangepi", "Instalando Gentoo en una Orange Pi", aarroyoc, "2024-09-17 20:26:00.00000", html("instalando-gentoo-orangepi.html"), public, ["programacion", "gentoo", "arm", "linux", "orangepi"]).
post("analizando-estadisticas-web-bajo-costo", "Analizando estadísticas web con bajo costo", aarroyoc, "2024-11-25 22:11:00.00000", html("analizando-estadisticas-web-bajo-coste.html"), public, ["programacion", "tutorial", "web", "python", "streamlit", "parquet", "azure"]).
post("videojuegos-2024", "Videojuegos de 2024", aarroyoc, "2024-12-24 00:02:00.00000", html("videojuegos-2024.html"), public, ["critica", "recapitulacion", "videojuegos"]).
post("feliz-navidad-2024", "Feliz Navidad 2024", aarroyoc, "2024-12-25 22:08:00.00000", html("feliz-navidad-2024.html"), public, ["felicitacion", "navidad"]).
post("que-paso-en-2024", "¿Qué pasó en 2024?", aarroyoc, "2025-01-03 18:20:00.00000", html("que-paso-en-2024.html"), public, ["personal", "trabajo"]).
post("entrevista-tecnolocuras", "Entrevista tecnolocuras.com", aarroyoc, "2025-03-06 23:07:00.00000", html("entrevista-tecnolocuras.html"), public, ["blog", "entrevista", "personal"]).
post("365-dias-de-chino-con-duolingo", "365 días de Chino con Duolingo", aarroyoc, "2025-04-25 20:35:00.00000", html("365-dias-de-chino-con-duolingo.html"), public, ["idiomas", "chino", "personal"]).
post("paralelismo-para-lelos", "Paralelismo para lelos", aarroyoc, "2025-07-07 22:27:00.00000", html("paralelismo-para-lelos.html"), public, ["programacion", "rust", "paralelismo"]).
post("paralelismo-para-lelos-2", "Paralelismo para lelos parte 2", aarroyoc, "2025-08-12 22:17:00.00000", html("paralelismo-para-lelos-2.html"), public, ["programacion", "rust", "paralelismo"]).
post("paralelismo-para-lelos-3", "Paralelismo para lelos parte 3: usando la GPU con WGPU", aarroyoc, "2025-08-28 20:10:00.00000", html("paralelismo-para-lelos-3.html"), public, ["programacion", "rust", "paralelismo", "gpu"]).
